### ISSUE TITLE
Cannot run “try before you buy” in Pokemon demo

### ISSUE THREAD

**Issue by tjvantoll** [EddyVerbruggen/nativescript-ar#74]
### Which platform(s) does your issue occur on?

Physical iPhone X running iOS 13.1

### Please, provide the following version numbers that your issue occurs with:

CLI: 6.1.0
Other versions will be latest because this occurs in the demo app.

### Please, tell us how to recreate the issue in as much detail as possible. 

I run the Pokémon demo from a fresh clone of the repo using `npm run demo.pokemon.ios` in the `src` directory.

The “augment card” and “search by card” pages work great, but as soon as I tap on “Try before you buy” the app crashes with this error.

```
file:///node_modules/nativescript-ar/ar.js:205:0: JS ERROR Error: This set of frame semantics is not supported on this configuration
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   _start@file:///node_modules/tns-core-modules/application/application.js:295:0
2   run@file:///node_modules/tns-core-modules/application/application.js:323:0
3   bootstrapNativeScriptApp@file:///node_modules/nativescript-angular/platform-common.js:210:0
4   bootstrapApp@file:///node_modules/nativescript-angular/platform-common.js:111:0
5   bootstrapModule@file:///node_modules/nativescript-angular/platform-common.js:91:0
6   @file:///app/bundle.js:395:144
7   ./main.ts@file:///app/bundle.js:400:34
8   __webpack_require__@file:///src/webpack/bootstrap:750:0
9   checkDeferredModules@file:///src/webpack/bootstrap:43:0
10  webpackJsonpCallback@file:///src/webpack/bootstrap:30:0
11  anonymous@file:///app/bundle.js:2:61
12  evaluate@[native code]
13  moduleEvaluation@:1:11
14  promiseReactionJob@:1:11
```

**Comment by EddyVerbruggen** [comment]
I'm afraid it's this one: https://stackoverflow.com/questions/57893809/is-arkit-3-people-occlusion-restrict-to-iphone-x-and-newer

So it's related to 'WORLD' tracking (and indeed that demo (and the solarsystem one)) uses that feature.

So people occlusion is not supported by your device and I didn't see it because oddly enough we don't have the same devices currently! 😘(11 Pro here). I can reproduce this by deploying to my iPad Pro running iOS 13.

I (the plugin) assumed this was an iOS 13 feature, but it's actually more restrictive. Let me add a check and push a new release.

**Comment by EddyVerbruggen** [comment]
Should be good now (1.0.1 / update the repo)!

**Comment by tjvantoll** [comment]
Perfect! This indeed fixed both the Pokémon and solar system demos for me 🤘

And let’s be honest, the real issue here is I somehow didn’t upgrade my phone when you did. I might need to fix that.

**Comment by EddyVerbruggen** [comment]
HAHA yes, focus on the right things mate - click, click: https://www.apple.com/shop/buy-iphone/iphone-11-pro
